const categories=['Все','Кольца','Серьги','Цепочки','Браслеты','Подвески','Комплекты','Другие украшения'];
const defaults={products:[
{id:1,name:'Кольцо «Луна»',category:'Кольца',assay:'585',weight:'2,84 г',price:89500,available:true,hidden:false,order:1,description:'Изящное кольцо из жёлтого золота с мягким сиянием. Лаконичный силуэт легко вписывается в повседневные и особенные образы.',image:'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=900&q=85'},
{id:2,name:'Серьги «Сияние»',category:'Серьги',assay:'585',weight:'3,12 г',price:112000,available:true,hidden:false,order:2,description:'Лёгкие серьги из золота 585 пробы. Чистая форма и деликатный блеск для тех, кто любит ненавязчивую роскошь.',image:'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=900&q=85'},
{id:3,name:'Цепочка «Тёплый свет»',category:'Цепочки',assay:'585',weight:'4,96 г',price:148000,available:true,hidden:false,order:3,description:'Классическая золотая цепочка с надёжным замком. Прекрасна соло и в сочетании с любимой подвеской.',image:'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=900&q=85'},
{id:4,name:'Браслет «Нить»',category:'Браслеты',assay:'585',weight:'3,67 г',price:106000,available:false,hidden:false,order:4,description:'Тонкий браслет, созданный для ежедневного сияния. Минималистичный акцент, который хочется не снимать.',image:'https://images.unsplash.com/photo-1611085583191-a3b181a88401?auto=format&fit=crop&w=900&q=85'},
{id:5,name:'Подвеска «Сердце»',category:'Подвески',assay:'585',weight:'1,72 г',price:64500,available:true,hidden:false,order:5,description:'Золотая подвеска как маленькое признание в любви. Бережная деталь для самого близкого человека.',image:'https://images.unsplash.com/photo-1598560917505-59a3ad559071?auto=format&fit=crop&w=900&q=85'},
{id:6,name:'Комплект «Amina»',category:'Комплекты',assay:'585',weight:'7,14 г',price:229000,available:true,hidden:false,order:6,description:'Серьги и подвеска в едином деликатном дизайне. Подарочный комплект, который будет радовать долгие годы.',image:'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=900&q=85'},
{id:7,name:'Кольцо «Звёздный свет»',category:'Кольца',assay:'585',weight:'2,31 г',price:127000,available:true,hidden:false,order:7,description:'Тонкое кольцо из жёлтого золота с сияющим акцентом. Нежное украшение для особого настроения.',image:'https://images.unsplash.com/photo-1589674781759-c21c37956a44?auto=format&fit=crop&w=900&q=85'},
{id:8,name:'Серьги «Медовый блеск»',category:'Серьги',assay:'585',weight:'4,26 г',price:159000,available:true,hidden:false,order:8,description:'Выразительные золотые серьги с гладкой полировкой и мягким тёплым блеском.',image:'https://images.unsplash.com/photo-1635767798638-3e25273a8236?auto=format&fit=crop&w=900&q=85'},
{id:9,name:'Подвеска «Солнце»',category:'Подвески',assay:'585',weight:'2,06 г',price:78500,available:true,hidden:false,order:9,description:'Миниатюрная золотая подвеска, которая ловит свет в каждом движении.',image:'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=900&q=85'},
{id:10,name:'Комплект «Noor» с бриллиантами',category:'Комплекты',assay:'585',weight:'6,85 г',price:418000,available:true,hidden:false,order:10,description:'Серьги и подвеска из золота 585 пробы, дополненные натуральными бриллиантами. Чистый блеск камней подчёркивает лаконичную геометрию комплекта.',image:'https://images.unsplash.com/photo-1603561596112-db1d26e1b6dd?auto=format&fit=crop&w=900&q=85'},
{id:11,name:'Комплект «Жемчужная линия»',category:'Комплекты',assay:'585',weight:'8,42 г',price:286000,available:true,hidden:false,order:11,description:'Воздушный комплект из серьг и кольца с культивированным жемчугом. Золото и перламутр — классика, которая всегда звучит современно.',image:'https://images.unsplash.com/photo-1596944946755-2ff867a8ebf2?auto=format&fit=crop&w=900&q=85'},
{id:12,name:'Комплект «Amethyst»',category:'Комплекты',assay:'585',weight:'9,17 г',price:352000,available:false,hidden:false,order:12,description:'Комплект из серьг и подвески с насыщенными аметистами огранки «овал». Глубокий фиолетовый оттенок особенно красиво раскрывается в тёплом золоте.',image:'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=900&q=85'},
{id:13,name:'Браслет «Golden Hour»',category:'Браслеты',assay:'585',weight:'5,48 г',price:173000,available:true,hidden:false,order:13,description:'Лёгкий браслет с выразительными золотыми звеньями для ежедневного сочетания с часами и кольцами.',image:'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=900&q=85'},
{id:14,name:'Цепочка «Venera»',category:'Цепочки',assay:'585',weight:'6,22 г',price:185000,available:true,hidden:false,order:14,description:'Изящная цепочка с ровным мягким сиянием. Подходит для кулона или самостоятельного образа.',image:'https://images.unsplash.com/photo-1599459183200-59c768b2445a?auto=format&fit=crop&w=900&q=85'}],
reviews:[{id:1,name:'Мадина',rating:5,text:'Очень аккуратное и красивое кольцо. В жизни сияет ещё нежнее, чем на фото. Спасибо за внимательное отношение!'},{id:2,name:'Айдана',rating:5,text:'Выбирала подарок маме — менеджер помог с размером и выбором. Серьги невероятно нежные, мама в восторге.'},{id:3,name:'Сабина',rating:5,text:'Люблю, когда украшения выглядят дорого, но не слишком броско. Мой браслет именно такой. Рекомендую Aikerim.'}],
contacts:{phone:'+7 777 000 00 00',whatsapp:'77770000000',instagram:'aikerim.jewelry',address:'г. Алматы, ул. Абая, 45',hours:'Ежедневно, 10:00–20:00'}};
let data=JSON.parse(localStorage.getItem('aikerim-data')||'null')||structuredClone(defaults);
// Добавляем новые демонстрационные позиции при обновлении витрины, сохраняя ручные правки владельца.
const knownIds=new Set(data.products.map(p=>p.id));const additions=defaults.products.filter(p=>!knownIds.has(p.id));if(additions.length){data.products.push(...structuredClone(additions));localStorage.setItem('aikerim-data',JSON.stringify(data))}let currentCategory='Все',tab='products';
const filtersEl=document.querySelector('#filters'),sortEl=document.querySelector('#sort'),productsEl=document.querySelector('#products'),reviewsList=document.querySelector('#reviews-list'),contactData=document.querySelector('#contact-data'),productModal=document.querySelector('#product-modal'),adminModal=document.querySelector('#admin-modal');
const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₸';const save=()=>localStorage.setItem('aikerim-data',JSON.stringify(data));
function render(){filtersEl.innerHTML=categories.map(c=>`<button class="${c===currentCategory?'active':''}" onclick="filterBy('${c}')">${c}</button>`).join('');let list=data.products.filter(p=>!p.hidden&&(currentCategory==='Все'||p.category===currentCategory));const sort=sortEl.value;if(sort==='asc')list.sort((a,b)=>a.price-b.price);else if(sort==='desc')list.sort((a,b)=>b.price-a.price);else list.sort((a,b)=>a.order-b.order);productsEl.innerHTML=list.map(p=>`<article class="product-card" onclick="showProduct(${p.id})"><div class="product-image"><img src="${p.image}" alt="${p.name}"><span class="availability">${p.available?'В НАЛИЧИИ':'ПОД ЗАКАЗ'}</span></div><div class="product-meta"><div><h3>${p.name}</h3><span class="price">${money(p.price)}</span></div><p>${p.category} · Золото ${p.assay} · ${p.weight}</p></div></article>`).join('')||'<p>В этой категории пока нет украшений.</p>';reviewsList.innerHTML=data.reviews.map(r=>`<article class="review"><div class="stars">${'★'.repeat(r.rating)}</div><p>«${r.text}»</p><strong>${r.name}</strong></article>`).join('');const c=data.contacts;contactData.innerHTML=`<div><label>Телефон</label><a href="tel:${c.phone.replace(/\s/g,'')}">${c.phone}</a></div><div><label>Instagram</label><a target="_blank" href="https://instagram.com/${c.instagram}">@${c.instagram}</a></div><div><label>Адрес</label>${c.address}</div><div><label>График</label>${c.hours}</div>`;document.querySelectorAll('[data-whatsapp]').forEach(a=>a.href=`https://wa.me/${c.whatsapp}?text=${encodeURIComponent('Здравствуйте! Хочу уточнить наличие украшения Aikerim.')}`)}
window.filterBy=c=>{currentCategory=c;render()};sortEl.onchange=render;
function showProduct(id){const p=data.products.find(x=>x.id===id);productModal.innerHTML=`<div class="modal-content"><img src="${p.image}" alt="${p.name}"><div class="modal-info"><button class="close" onclick="productModal.close()">×</button><p class="eyebrow">${p.category.toUpperCase()}</p><h2>${p.name}</h2><h3>${money(p.price)}</h3><p>${p.description}</p><p><b>Проба:</b> золото ${p.assay}<br><b>Вес:</b> ${p.weight}<br><b>Наличие:</b> ${p.available?'в наличии':'под заказ'}</p><a class="button" href="https://wa.me/${data.contacts.whatsapp}?text=${encodeURIComponent('Здравствуйте! Меня интересует '+p.name+' за '+money(p.price))}" target="_blank">Заказать <span>→</span></a></div></div>`;productModal.showModal()}window.showProduct=showProduct;
function admin(){adminModal.innerHTML=`<div class="admin-head"><div><p class="eyebrow">ПАНЕЛЬ УПРАВЛЕНИЯ</p><h2>Aikerim</h2></div><button class="close" onclick="adminModal.close()">×</button></div><div class="admin-body"><div class="notice">Все изменения сохраняются в этом браузере и сразу отражаются в каталоге.</div><div class="admin-nav"><button class="${tab==='products'?'active':''}" onclick="setTab('products')">Товары</button><button class="${tab==='reviews'?'active':''}" onclick="setTab('reviews')">Отзывы</button><button class="${tab==='contacts'?'active':''}" onclick="setTab('contacts')">Контакты</button></div><div id="admin-content"></div></div>`;renderAdmin();adminModal.showModal()}document.querySelector('.admin-trigger').onclick=admin;document.querySelector('.footer-admin').onclick=admin;
window.setTab=t=>{tab=t;admin()};
function renderAdmin(){const el=document.querySelector('#admin-content');if(tab==='products'){el.innerHTML=`<button class="add-btn" onclick="editProduct()">+ Добавить товар</button><table class="admin-list">${data.products.sort((a,b)=>a.order-b.order).map(p=>`<tr><td><img src="${p.image}"></td><td><b>${p.name}</b><br>${money(p.price)} · ${p.hidden?'скрыт':p.available?'в наличии':'под заказ'}</td><td><button class="icon-btn" onclick="editProduct(${p.id})">Изменить</button><button class="icon-btn" onclick="toggleProduct(${p.id})">${p.hidden?'Показать':'Скрыть'}</button><button class="icon-btn danger" onclick="deleteProduct(${p.id})">Удалить</button></td></tr>`).join('')}</table>`}else if(tab==='reviews'){el.innerHTML=`<button class="add-btn" onclick="editReview()">+ Добавить отзыв</button><table class="admin-list">${data.reviews.map(r=>`<tr><td><b>${r.name}</b><br>${r.text}</td><td><button class="icon-btn" onclick="editReview(${r.id})">Изменить</button><button class="icon-btn danger" onclick="deleteReview(${r.id})">Удалить</button></td></tr>`).join('')}</table>`}else{let c=data.contacts;el.innerHTML=`<div class="admin-grid"><label>Телефон<input id="phone" value="${c.phone}"></label><label>WhatsApp (только цифры)<input id="whatsapp" value="${c.whatsapp}"></label><label>Instagram без @<input id="instagram" value="${c.instagram}"></label><label>Адрес<input id="address" value="${c.address}"></label><label>График<input id="hours" value="${c.hours}"></label></div><div class="admin-actions"><button class="save-btn" onclick="saveContacts()">Сохранить контакты</button></div>`}}
window.editProduct=id=>{let p=id?data.products.find(x=>x.id===id):{id:Date.now(),name:'',category:'Кольца',assay:'585',weight:'',price:'',available:true,hidden:false,order:data.products.length+1,description:'',image:''};document.querySelector('#admin-content').innerHTML=`<p class="eyebrow">${id?'РЕДАКТИРОВАНИЕ':'НОВЫЙ ТОВАР'}</p><div class="admin-grid"><label>Название<input id="name" value="${p.name}"></label><label>Категория<select id="category">${categories.slice(1).map(c=>`<option ${c===p.category?'selected':''}>${c}</option>`).join('')}</select></label><label>Цена, ₸<input id="price" type="number" value="${p.price}"></label><label>Проба<input id="assay" value="${p.assay}"></label><label>Вес<input id="weight" value="${p.weight}"></label><label>Порядок показа<input id="order" type="number" value="${p.order}"></label><label>Фото — ссылка<input id="image" value="${p.image}"></label><label>Наличие<select id="available"><option value="true" ${p.available?'selected':''}>В наличии</option><option value="false" ${!p.available?'selected':''}>Под заказ</option></select></label><label style="grid-column:1/-1">Описание<textarea id="description">${p.description}</textarea></label></div><div class="admin-actions"><button class="save-btn" onclick="saveProduct(${p.id},${!!id})">Сохранить</button><button class="icon-btn" onclick="renderAdmin()">Отмена</button></div>`};
window.saveProduct=(id,exists)=>{let p={id,name:name.value,category:category.value,price:+price.value,assay:assay.value,weight:weight.value,order:+order.value,available:available.value==='true',image:image.value||defaults.products[0].image,description:description.value,hidden:false};if(exists){let old=data.products.find(x=>x.id===id);p.hidden=old.hidden;Object.assign(old,p)}else data.products.push(p);save();render();renderAdmin()};window.toggleProduct=id=>{let p=data.products.find(x=>x.id===id);p.hidden=!p.hidden;save();render();renderAdmin()};window.deleteProduct=id=>{if(confirm('Удалить товар без возможности восстановления?')){data.products=data.products.filter(x=>x.id!==id);save();render();renderAdmin()}};
window.editReview=id=>{let r=id?data.reviews.find(x=>x.id===id):{id:Date.now(),name:'',rating:5,text:''};document.querySelector('#admin-content').innerHTML=`<div class="admin-grid"><label>Имя<input id="rname" value="${r.name}"></label><label>Рейтинг (1–5)<input id="rating" type="number" min="1" max="5" value="${r.rating}"></label><label style="grid-column:1/-1">Текст<textarea id="rtext">${r.text}</textarea></label></div><div class="admin-actions"><button class="save-btn" onclick="saveReview(${r.id},${!!id})">Сохранить</button><button class="icon-btn" onclick="renderAdmin()">Отмена</button></div>`};window.saveReview=(id,exists)=>{let r={id,name:rname.value,rating:+rating.value,text:rtext.value};if(exists)Object.assign(data.reviews.find(x=>x.id===id),r);else data.reviews.push(r);save();render();renderAdmin()};window.deleteReview=id=>{data.reviews=data.reviews.filter(x=>x.id!==id);save();render();renderAdmin()};window.saveContacts=()=>{for(let key of ['phone','whatsapp','instagram','address','hours'])data.contacts[key]=document.querySelector('#'+key).value;save();render();renderAdmin()};
render();
